spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  docker:
    compose:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: pet-location